---
   - name: Install mariadb package
     yum: name=mariadb-server,mariadb state=present
    #sudo: yes
     when: ansible_os_family == "RedHat"

   - name: Starting mariadb service
     service: name=mariadb state=started enabled=yes

     notify:
        - restart mariadb

...
