---
   - name: Install php and extensions
     yum: name=php71u,php71u-mysqlnd,php71u-pdo,php71u-gd,php71u-snmp,php71u-mbstring,php71u-bcmath,php71u-ldap,php71u-json state=present
#  sudo: yes
     when: ansible_os_family == "RedHat"


   - name: Creating phpinfo file
     shell: echo '<?php echo phpinfo(); ?>' > /var/www/html/info.php
     notify:
       - restart httpd

...
