---
   - name: Install httpd package
     yum: name=httpd state=present
    #sudo: yes
     when: ansible_os_family == "RedHat"

   - name: Starting httpd service
     service: name=httpd state=started enabled=yes

     notify:
        - restart httpd

...
