---
   - name: Copy charachter set of Mysql server to utf8
     blockinfile:
       dest: /etc/my.cnf.d/server.cnf
       block: |
         character-set-server = utf8
         collation-server = utf8_general_ci
         skip-character-set-client-handshake
       insertafter:  '^\[server\]'
#       owner: foo
#       group: foo
#       mode: 0644
       backup: yes
     tags: utf8

     notify:
       - restart mariadb
...
