---
 - hosts: servers
   remote_user: root

   tasks:
     - include: tasks/install-apache.yml
     - include: tasks/install-mariadb.yml
     - include: tasks/install-mysqlpython.yml
     - include: tasks/mariadb.yml
     - include: tasks/utf8cnf.yml
     - meta: flush_handlers
     - include: tasks/install-phpex.yml
     - include: tasks/install-git.yml


     - name: Create racktables user
       user: name=racktables shell=/sbin/nologin comment="RackTables User" createhome=yes home=/home/racktables


     - name: Download RackTables-0.20.14
       git: 
         repo: https://github.com/RackTables/racktables.git
         dest: /tmp/racktables
       tags: git  


     - name: Copy RackTables-0.20.14 wwwroot
       shell: cp -rf /tmp/racktables/wwwroot/ /var/www/html/racktables

     - name: Change ownership for copied catalog
       shell: chown -R racktables:racktables /var/www/html/racktables

     - include: tasks/rackconf.yml
     - meta: flush_handlers


     - name: Serch secret.php is available
       stat: 
         path: /var/www/html/racktables/inc/secret.php
       register: result

     - name: Create secret.php file, if it doesnt exist
       file:
         path: /var/www/html/racktables/inc/secret.php
         owner: apache
         group: apache
         mode:  a=rw
         state: touch 
       when: result.stat.exists == False
       tags: file

     - firewalld:
         service: http
         permanent: true
         state: enabled
       tags: firewall
       notify:
         - restart firewalld
     - meta: flush_handlers


     - selinux:
#         permanent: true
         state: disabled


     - name: Wait until the string Username is in the file secret.php before continuing >
             open http://Server-IP/racktables/?module=installer  you have 
       wait_for:
         path: /var/www/html/racktables/inc/secret.php
         search_regex: username
         delay: 80 
       tags: wait


     - name: RackTables installation step 4 of 7
       shell: chmod 440 /var/www/html/racktables/inc/secret.php
       tags: chors


   handlers:
     - name: restart httpd
       service: name=httpd state=restarted
    
     - name: restart mariadb
       service: name=mariadb state=restarted

     - name: restart firewalld
       service: name=firewalld state=restarted


...
