---
 - hosts: servers
   remote_user: root

   tasks:
     - include: tasks/install-apache.yml
     - include: tasks/install-mariadb.yml
     - include: tasks/install-mysqlpython.yml
     - include: tasks/mariadb.yml
     - include: tasks/utf8cnf.yml
     - meta: flush_handlers
     - include: tasks/install-ius.yml
     - include: tasks/install-phpex.yml
     - include: tasks/install-git.yml


     - name: Create racktables user
       user: name=racktables shell=/sbin/nologin comment="RackTables User" createhome=yes home=/home/racktables


     - name: Download RackTables
       git: 
         repo: https://github.com/RackTables/racktables.git
         dest: /var/www/html/racktables/
       tags: git  


#     - name: Copy RackTables to wwwroot
#       shell: cp -rf /tmp/racktables/wwwroot/ /var/www/html/racktables/
#       command: cp -rf /tmp/racktables/wwwroot/ /var/www/html/racktables
#       tags: cp

     - name: Change ownership /var/www/html/racktables/ catalog
       file: 
         path: /var/www/html/racktables
         owner: racktables
         group: racktables
         state: directory

     - include: tasks/rackconf.yml
     - meta: flush_handlers


     - name: Serch secret.php is available
       stat: 
         path: /var/www/html/racktables/wwwroot/inc/secret.php
       register: result

     - name: Create secret.php file, if it doesnt exist
       file:
         path: /var/www/html/racktables/wwwroot/inc/secret.php
         owner: apache
         group: apache
         mode:  a=rw
         state: touch 
       when: result.stat.exists == False
       tags: file

     - firewalld:
         service: http
         permanent: true
         state: enabled
       tags: firewall
       notify:
         - restart firewalld
     - meta: flush_handlers


     - selinux:
#         permanent: true
         state: disabled


     - name: Wait until the string Username is in the file secret.php before continuing >
             open http://Server-IP/racktables/?module=installer
       wait_for:
         path: /var/www/html/racktables/wwwroot/inc/secret.php
         search_regex: username
         delay: 60 
       tags: wait


     - name: RackTables installation step 4 of 7
       file: 
         path: /var/www/html/racktables/wwwroot/inc/secret.php
         owner: apache
         group: apache
         mode: 0440
       tags: chors


   handlers:
     - name: restart httpd
       service: name=httpd state=restarted
    
     - name: restart mariadb
       service: name=mariadb state=restarted

     - name: restart firewalld
       service: name=firewalld state=restarted


...
